name: tesk-api

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]

  workflow_dispatch:
    inputs:
      profile:
        description: Profile name
        required: false
        default: tesk-api


jobs:
  build-from-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout elixir-cloud-aai/tesk-api
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      
      - name: Build with Maven
        run: bash -c './mvnw clean verify'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set Variables
        shell: bash
        run: |
          echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/*/} | tr / _)"
          echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/*/} | tr / _)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: quay.io/cdis/tesk-api:${{ env.IMAGE_TAG }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            quay.io/cdis/tesk-api:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
